on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  checkov-scan:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - run: pip install checkov
      - run: checkov -d .


  
  